/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Supermarket;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.SupermarketOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Trupti
 */
public class SupermarketWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    SupermarketOrganization organization;
    Enterprise enterprise;
    EcoSystem business;
    /**
     * Creates new form DonorOptions
     */
   
    public SupermarketWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SupermarketOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donateFoodTabBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        donateFoodTabBtn.setFont(new java.awt.Font("Lucida Fax", 2, 12)); // NOI18N
        donateFoodTabBtn.setText("Donate Food");
        donateFoodTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateFoodTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(donateFoodTabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(donateFoodTabBtn)
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void donateFoodTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateFoodTabBtnActionPerformed
        // TODO add your handling code here:
        DonateFood df = new DonateFood(userProcessContainer, account, organization, enterprise,business);
        userProcessContainer.add("DonateFood", df);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_donateFoodTabBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donateFoodTabBtn;
    // End of variables declaration//GEN-END:variables
}
