/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CommunityCenter;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CommunityCenterOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Trupti
 */
public class CommunityCenterWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem system;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private CommunityCenterOrganization organization;
    /**
     * Creates new form CommunityCenterOptions
     */


    public CommunityCenterWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account,CommunityCenterOrganization organization) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization=organization;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postRequirementTab = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        postRequirementTab.setBackground(new java.awt.Color(255, 255, 255));
        postRequirementTab.setFont(new java.awt.Font("Lucida Fax", 2, 12)); // NOI18N
        postRequirementTab.setText("Post MedicalCamp Requirement");
        postRequirementTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postRequirementTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(postRequirementTab, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(postRequirementTab, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void postRequirementTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postRequirementTabActionPerformed
       PostAMedicalCampRequirement pam = new PostAMedicalCampRequirement(userProcessContainer ,userAccount ,system, enterprise, organization);
        userProcessContainer.add("PostAMedicalCampRequirement", pam);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_postRequirementTabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton postRequirementTab;
    // End of variables declaration//GEN-END:variables
}
