/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.CommunityCenterOrganization;
import Business.Organization.HospitalOrganization;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author Trupti
 */
public class HospitalWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    HospitalOrganization organization;
    CommunityCenterOrganization organization2;
    Enterprise enterprise;
    EcoSystem business;
    /**
     * Creates new form HospitalWorkAreaJPanel
     */
    public HospitalWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,HospitalOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.organization2 = organization2;
        this.enterprise = enterprise;
        this.business=business;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewRequirementMedicalCampTabBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        viewRequirementMedicalCampTabBtn.setFont(new java.awt.Font("Lucida Fax", 2, 12)); // NOI18N
        viewRequirementMedicalCampTabBtn.setText("View Medical Camp Requests");
        viewRequirementMedicalCampTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequirementMedicalCampTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(viewRequirementMedicalCampTabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(viewRequirementMedicalCampTabBtn)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewRequirementMedicalCampTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequirementMedicalCampTabBtnActionPerformed
        // TODO add your handling code here:
        MedicalCampRequestsJPanel mcrvp = new MedicalCampRequestsJPanel(userProcessContainer, account, organization, enterprise, business);
        userProcessContainer.add("MedicalCampRequestJPanel", mcrvp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewRequirementMedicalCampTabBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton viewRequirementMedicalCampTabBtn;
    // End of variables declaration//GEN-END:variables
}
