/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.CommunityCenterOrganization;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicalCampWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.CommunityCenter.PostAMedicalCampRequirement;

/**
 *
 * @author Trupti
 */
public class MedicalCampRequestsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private HospitalOrganization hospitalOrganization;
    private MedicalCampWorkRequest medicalCampWorkRequest;
    private Enterprise enterprise;

    /**
     * Creates new form ShowOverAllRequirementJPanel
     */
    public MedicalCampRequestsJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.business = business;
        this.hospitalOrganization = (HospitalOrganization) organization;

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewRequirementsTabBtn1 = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicalcampTbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        viewRequirementsTabBtn1.setFont(new java.awt.Font("Lucida Fax", 2, 12)); // NOI18N
        viewRequirementsTabBtn1.setText("View");
        viewRequirementsTabBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequirementsTabBtn1ActionPerformed(evt);
            }
        });

        assignJButton.setFont(new java.awt.Font("Lucida Fax", 2, 12)); // NOI18N
        assignJButton.setText("Assign this request to Me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        medicalcampTbl.setFont(new java.awt.Font("Lucida Fax", 2, 12)); // NOI18N
        medicalcampTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Requestor Name", "Status", "Details", "Approver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        medicalcampTbl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                medicalcampTblComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(medicalcampTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(viewRequirementsTabBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assignJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewRequirementsTabBtn1)
                    .addComponent(assignJButton))
                .addGap(213, 213, 213))
        );
    }// </editor-fold>//GEN-END:initComponents
public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) medicalcampTbl.getModel();

        model.setRowCount(0);

        System.out.println(business.getName());
        for (Organization orga : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (orga instanceof CommunityCenterOrganization) {
                for (WorkRequest request : orga.getWorkQueue().getWorkRequestList()) {
                    Object[] row = new Object[4];

                    row[0] = request;
                    row[1] = request.getStatus();
                    row[2] = request.getDetails();

                    row[3] = request.getApproverName() == null ? null : request.getApproverName().getEmployee().getName();

                    model.addRow(row);
                }
            }
        }

    }
    private void viewRequirementsTabBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequirementsTabBtn1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = medicalcampTbl.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        WorkRequest request = (WorkRequest) medicalcampTbl.getValueAt(selectedRow, 0);

        request.setStatus("Processing");

        ViewMedicalCampsRequestsJPanel viewMedicalCampsRequestsJPanel = new ViewMedicalCampsRequestsJPanel(userProcessContainer, (MedicalCampWorkRequest) request, userAccount, enterprise);
        userProcessContainer.add("viewMedicalCampsRequestsJPanel", viewMedicalCampsRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_viewRequirementsTabBtn1ActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = medicalcampTbl.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        WorkRequest request = (WorkRequest) medicalcampTbl.getValueAt(selectedRow, 0);
        request.setApproverName(userAccount);
        request.setStatus("Pending");
        populateTable();
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void medicalcampTblComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_medicalcampTblComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalcampTblComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable medicalcampTbl;
    private javax.swing.JButton viewRequirementsTabBtn1;
    // End of variables declaration//GEN-END:variables
}
